arb-dir: lib/src/localization/data/translations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
untranslated-messages-file: .dart_tool/flutter_gen/gen_l10n/untranslated_messages.txt